name: Pranay Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: 2. Print a greeting
        run: echo "Starting the automated workflow for Pranay"

      - name: 3. Check Python Version
        run: python --version

      - name: 4. List Repository Files
        run: ls -R
